services:
    guardsarm.base:
        build:
            context: ./guardsarm-base
            args:
                GUARDSARM_BRANCH: ${GUARDSARM_BRANCH}
        pull_policy: never
        image: guardsarm-base
        networks:
            - guardsarm.net

    certs.generator:
        build:
            context: ./certs-generator
        image: guardsarm-certs-generator
        pull_policy: never
        volumes:
            - guardsarm-certs:/certificates
            - ./config/guardsarm_dashboard_certs:/export/dashboard
            - ./certs-generator/config.yml:/tmp/config.yml:ro
        restart: "no"
        networks:
            - guardsarm.net

    guardsarm.indexer:
        image: quay.io/guardsarm/guardsarm-indexer:5.0.0-0
        container_name: guardsarm.indexer
        hostname: guardsarm.indexer
        ports:
            - "9200:9200"
        networks:
            guardsarm.net:
                aliases:
                    - guardsarm.indexer
        volumes:
            - guardsarm-indexer-data:/var/lib/guardsarm-indexer
            - guardsarm-certs:/etc/guardsarm-indexer/certs
            - ./guardsarm-indexer/guardsarm.indexer.yml:/usr/share/guardsarm-indexer/config/opensearch.yml:ro
        environment:
            - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
        depends_on:
            certs.generator:
                condition: service_completed_successfully
        healthcheck:
            test: ["CMD", "curl", "-k", "-u", "admin:admin", "https://localhost:9200/_cluster/health"]
            interval: 10s
            timeout: 5s
            retries: 20
            start_period: 120s

    guardsarm.manager:
        build:
            context: ./guardsarm-manager
            target: server
        pull_policy: never
        image: guardsarm-manager
        hostname: guardsarm.manager
        networks:
            - guardsarm.net
        ports:
            - "55050:55000"
        volumes:
            - guardsarm-certs:/var/guardsarm-manager/etc/certs
            - ${GUARDSARM_LOCAL_PATH}/framework/scripts:/var/guardsarm-manager/framework/scripts
            - ${GUARDSARM_LOCAL_PATH}/api/scripts:/var/guardsarm-manager/api/scripts
            - ${GUARDSARM_LOCAL_PATH}/framework/guardsarm:/var/guardsarm-manager/framework/python/lib/python${GUARDSARM_PYTHON_VERSION}/site-packages/guardsarm
            - ${GUARDSARM_LOCAL_PATH}/api/api:/var/guardsarm-manager/framework/python/lib/python${GUARDSARM_PYTHON_VERSION}/site-packages/api
        environment:
            OPENDISTRO_SECURITY_ENABLED: "false"
            NODE_NAME: "guardsarm.manager"
        entrypoint:
            - /scripts/entrypoint.sh
            - guardsarm.manager
            - master-node
            - master
        depends_on:
            guardsarm.indexer:
                condition: service_healthy
            guardsarm.base:
                condition: service_started

    guardsarm.worker1:
        image: guardsarm-manager
        hostname: guardsarm.worker1
        pull_policy: never
        networks:
            guardsarm.net:
                aliases:
                    - guardsarm.worker
        volumes:
            - guardsarm-certs:/var/guardsarm-manager/etc/certs
            - ${GUARDSARM_LOCAL_PATH}/framework/scripts:/var/guardsarm-manager/framework/scripts
            - ${GUARDSARM_LOCAL_PATH}/api/scripts:/var/guardsarm-manager/api/scripts
            - ${GUARDSARM_LOCAL_PATH}/framework/guardsarm:/var/guardsarm-manager/framework/python/lib/python${GUARDSARM_PYTHON_VERSION}/site-packages/guardsarm
            - ${GUARDSARM_LOCAL_PATH}/api/api:/var/guardsarm-manager/framework/python/lib/python${GUARDSARM_PYTHON_VERSION}/site-packages/api
        depends_on:
            guardsarm.manager:
                condition: service_started
        environment:
            NODE_NAME: "guardsarm.worker1"
        ports:
            - "55051:55000"
        entrypoint:
            - /scripts/entrypoint.sh
            - guardsarm.worker1
            - worker

    guardsarm.worker2:
        image: guardsarm-manager
        hostname: guardsarm.worker2
        pull_policy: never
        networks:
            guardsarm.net:
                aliases:
                    - guardsarm2.worker
        volumes:
            - guardsarm-certs:/var/guardsarm-manager/etc/certs
            - ${GUARDSARM_LOCAL_PATH}/framework/scripts:/var/guardsarm-manager/framework/scripts
            - ${GUARDSARM_LOCAL_PATH}/api/scripts:/var/guardsarm-manager/api/scripts
            - ${GUARDSARM_LOCAL_PATH}/framework/guardsarm:/var/guardsarm-manager/framework/python/lib/python${GUARDSARM_PYTHON_VERSION}/site-packages/guardsarm
            - ${GUARDSARM_LOCAL_PATH}/api/api:/var/guardsarm-manager/framework/python/lib/python${GUARDSARM_PYTHON_VERSION}/site-packages/api
        depends_on:
            guardsarm.manager:
                condition: service_started
        environment:
            NODE_NAME: "guardsarm.worker2"
        ports:
            - "55052:55000"
        entrypoint:
            - /scripts/entrypoint.sh
            - guardsarm.worker2
            - worker

    nginx.lb:
        build:
            context: ./nginx-lb
        image: nginx.lb
        pull_policy: never
        restart: on-failure:5
        ports:
            - "1514:1514"
        networks:
            guardsarm.net:
                aliases:
                    - nginx.lb
        depends_on:
            guardsarm.manager:
                condition: service_started
            guardsarm.worker1:
                condition: service_started
            guardsarm.worker2:
                condition: service_started
        entrypoint:
            - /scripts/entrypoint.sh

    guardsarm.agent:
        build:
            context: ./guardsarm-agent
        image: guardsarm-agent
        pull_policy: never
        networks:
            - guardsarm.net
        entrypoint:
            - /scripts/entrypoint.sh
            - nginx.lb
            - ${GUARDSARM_VERSION}
        depends_on:
            nginx.lb:
                condition: service_started

    guardsarm.dashboard:
        image: public.ecr.aws/guardsarm-cicd/guardsarm/guardsarm-dashboard:5.0.0-latest
        container_name: guardsarm.dashboard
        hostname: guardsarm.dashboard
        networks:
            - guardsarm.net
        ports:
            - "443:5601"
        volumes:
            - ./config/guardsarm_dashboard_certs:/tmp/certs
            - ./guardsarm-dashboard/guardsarm.dashboard.yml:/usr/share/guardsarm-dashboard/config/opensearch_dashboards.yml:ro
            - guardsarm-dashboard-custom:/usr/share/guardsarm-dashboard/plugins/guardsarm/public/assets/custom
        depends_on:
            guardsarm.indexer:
                condition: service_healthy

volumes:
  guardsarm-indexer-data:
  guardsarm-certs:
  guardsarm-dashboard-custom:

networks:
  guardsarm.net:
    driver: bridge
