nodes:
  indexer:
    - name: guardsarm.indexer
      ip: guardsarm.indexer

  server:
    - name: guardsarm.manager
      ip: guardsarm.manager
      node_type: master
    - name: guardsarm.worker1
      ip: guardsarm.worker
      node_type: worker
    - name: guardsarm.worker2
      ip: guardsarm2.worker
      node_type: worker
  dashboard:
    - name: guardsarm.dashboard
      ip: guardsarm.dashboard
