name: dev-env-engine

services:
  guardsarm-indexer:
    build:
      context: ./guardsarm-indexer
    image: dev-guardsarm-indexer
    pull_policy: build
    hostname: guardsarm-indexer
    container_name: guardsarm-indexer
    entrypoint: ["/entrypoint.sh"]
    volumes:
      - ./guardsarm-indexer/entrypoint.sh:/entrypoint.sh:ro
      - ./certs:/certs:ro
      - guardsarm-indexer-data:/var/lib/guardsarm-indexer
      - guardsarm-indexer-config:/etc/guardsarm-indexer-init
      - guardsarm-indexer-engine:/usr/share/guardsarm-indexer/engine
    ports:
      - 9200:9200

  guardsarm-dashboard:
    build:
        context: ./guardsarm-dashboard
    image: dev-guardsarm-dashboard
    pull_policy: build
    hostname: guardsarm-dashboard
    container_name: guardsarm-dashboard
    entrypoint: ["/entrypoint.sh"]
    volumes:
      - ./guardsarm-dashboard/entrypoint.sh:/entrypoint.sh:ro
      - ./certs:/certs:ro
    ports:
      - 443:443
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - guardsarm-indexer

volumes:
  guardsarm-indexer-data:
    driver: local
  guardsarm-indexer-config:
    driver: local
  guardsarm-indexer-engine:
    driver: local
