#include <gtest/gtest.h>

#include "hlp_test.hpp"

auto constexpr NAME = "quotedParser";
static const std::string TARGET = "/TargetField";

INSTANTIATE_TEST_SUITE_P(QuotedBuild,
                         HlpBuildTest,
                         ::testing::Values(BuildT(SUCCESS, getQuotedParser, {NAME, TARGET, {}, {}}),
                                           BuildT(SUCCESS, getQuotedParser, {NAME, TARGET, {}, {"q"}}),
                                           BuildT(SUCCESS, getQuotedParser, {NAME, TARGET, {}, {"q", "e"}}),
                                           BuildT(FAILURE, getQuotedParser, {NAME, TARGET, {}, {"quoted"}}),
                                           BuildT(FAILURE, getQuotedParser, {NAME, TARGET, {}, {"q", "escape"}}),
                                           BuildT(FAILURE, getQuotedParser, {NAME, TARGET, {}, {"q", "e", "?"}})));

INSTANTIATE_TEST_SUITE_P(QuotedParse,
                         HlpParseTest,
                         ::testing::Values(
                             // Default parameters
                             ParseT(FAILURE, "guardsarm", {}, 0, getQuotedParser, {NAME, TARGET, {}, {}}),
                             ParseT(FAILURE, R"("guardsarm 123)", {}, 0, getQuotedParser, {NAME, TARGET, {}, {}}),
                             ParseT(SUCCESS,
                                    R"("GuardSarm" 123)",
                                    j(fmt::format(R"({{"{}":"GuardSarm"}})", TARGET.substr(1))),
                                    7,
                                    getQuotedParser,
                                    {NAME, TARGET, {}, {}}),
                             ParseT(SUCCESS,
                                    R"("GuardSarm")",
                                    j(fmt::format(R"({{"{}":"GuardSarm"}})", TARGET.substr(1))),
                                    7,
                                    getQuotedParser,
                                    {NAME, TARGET, {}, {}}),
                             ParseT(SUCCESS,
                                    R"("hi my name is \"GuardSarm\"")",
                                    j(fmt::format(R"({{"{}":"hi my name is \"GuardSarm\""}})", TARGET.substr(1))),
                                    25,
                                    getQuotedParser,
                                    {NAME, TARGET, {}, {}}),
                             ParseT(SUCCESS,
                                    R"("hi my name is \"GuardSarm\"" 123456)",
                                    j(fmt::format(R"({{"{}":"hi my name is \"GuardSarm\""}})", TARGET.substr(1))),
                                    25,
                                    getQuotedParser,
                                    {NAME, TARGET, {}, {}}),
                             // Change " to '
                             ParseT(FAILURE, "guardsarm'", {}, 0, getQuotedParser, {NAME, TARGET, {}, {"'"}}),
                             ParseT(FAILURE, R"('guardsarm 123)", {}, 0, getQuotedParser, {NAME, TARGET, {}, {"'"}}),
                             ParseT(SUCCESS,
                                    R"('GuardSarm' 123)",
                                    j(fmt::format(R"({{"{}":"GuardSarm"}})", TARGET.substr(1))),
                                    7,
                                    getQuotedParser,
                                    {NAME, TARGET, {}, {"'"}}),
                             ParseT(SUCCESS,
                                    R"('GuardSarm')",
                                    j(fmt::format(R"({{"{}":"GuardSarm"}})", TARGET.substr(1))),
                                    7,
                                    getQuotedParser,
                                    {NAME, TARGET, {}, {"'"}}),
                             ParseT(SUCCESS,
                                    R"('hi my name is \'GuardSarm\'')",
                                    j(fmt::format(R"({{"{}":"hi my name is 'GuardSarm'"}})", TARGET.substr(1))),
                                    25,
                                    getQuotedParser,
                                    {NAME, TARGET, {}, {"'"}}),
                             ParseT(SUCCESS,
                                    R"('hi my name is \'GuardSarm\'' 123456)",
                                    j(fmt::format(R"({{"{}":"hi my name is 'GuardSarm'"}})", TARGET.substr(1))),
                                    25,
                                    getQuotedParser,
                                    {NAME, TARGET, {}, {"'"}}),
                             // Change " to ' and \ to :
                             ParseT(FAILURE, "guardsarm'", {}, 0, getQuotedParser, {NAME, TARGET, {}, {"'", ":"}}),
                             ParseT(FAILURE, R"('guardsarm 123)", {}, 0, getQuotedParser, {NAME, TARGET, {}, {"'", ":"}}),
                             ParseT(SUCCESS,
                                    R"('GuardSarm' 123)",
                                    j(fmt::format(R"({{"{}":"GuardSarm"}})", TARGET.substr(1))),
                                    7,
                                    getQuotedParser,
                                    {NAME, TARGET, {}, {"'", ":"}}),
                             ParseT(SUCCESS,
                                    R"('GuardSarm')",
                                    j(fmt::format(R"({{"{}":"GuardSarm"}})", TARGET.substr(1))),
                                    7,
                                    getQuotedParser,
                                    {NAME, TARGET, {}, {"'", ":"}}),
                             ParseT(SUCCESS,
                                    R"('hi my name is :'GuardSarm:'')",
                                    j(fmt::format(R"({{"{}":"hi my name is 'GuardSarm'"}})", TARGET.substr(1))),
                                    25,
                                    getQuotedParser,
                                    {NAME, TARGET, {}, {"'", ":"}}),
                             ParseT(SUCCESS,
                                    R"('hi my name is :'GuardSarm:'' 123456)",
                                    j(fmt::format(R"({{"{}":"hi my name is 'GuardSarm'"}})", TARGET.substr(1))),
                                    25,
                                    getQuotedParser,
                                    {NAME, TARGET, {}, {"'", ":"}})));

//         // TODO: We want to support this case ?
//         // Mantain " but change escape character to " (Like CSV files)
//         // TestCase {R"(guardsarm")", false, {""}, Options {"\"", "\""}, fn(R"({})"), 0},
//         // TestCase {R"("guardsarm 123)", false, {""}, Options {"\"", "\""}, fn(R"({})"), 10},
//         // TestCase {
//         //     R"("GuardSarm" 123)", true, {""}, Options {"\"", "\""}, fn(R"("GuardSarm")"), 7},
//         // TestCase {R"("GuardSarm")", true, {""}, Options {"\"", "\""}, fn(R"("GuardSarm")"), 7},
//         // TestCase {R"("hi my name is ""GuardSarm""")",
//         //           true,
//         //           {""},
//         //           Options {"\"", "\""},
//         //           fn(R"("hi my name is \"GuardSarm\"")"),
//         //           25},
//         // TestCase {R"("hi my name is ""GuardSarm"" 123456)",
//         //           true,
//         //           {""},
//         //           Options {"\"", "\""},
//         //           fn(R"("hi my name is \"GuardSarm\"")"),
//         //           25}
